spring:
  rabbitmq:
    addresses: 127.0.0.1
    port: 5672  # localhost:15672 ??: 15672?? admin web? ???, JAVA? ???? 5672? ???
    username: admin
    password: admin
    cache:
      channel:
        size: 10
      connection:
        size: 10
      publisher-confirms: true
