#jar 시킬때 파람을 줘서 job을 실행 시킬 수 있다. none은 jar을 시행할때 어떤 파람을 안주면 실행을 안하게 설정
server:
  port: 6060

#Redis
redis:
  host: 127.0.0.1
  port: 6379

spring:
  profiles:
    active: local
  # BATCH
  batch:
    job:
      enabled: false
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true # 외부에서 접속 허용
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  # JPA
  jpa:
    hibernate:
      ddl-auto: create  # 자동으로 테이블 생성 (drop->create) # 선언 안할시, 스프링부트는 create-drop으로 실행 (마지막에 drop 한다-초기화)
    properties:
      hibernate:
        show_sql: true  # 실행 SQL (System.out) - 운영에서 찍으면 안되므로 주석처리
        format_sql: true