server:
  port: 5050

#spring:
#  security:
#    oauth2:
#      client: # provider 은 구글이 등록해놔서 따로 설정하지 않아도 된다. (이미 common 에)
#        registration:
#          google: # Registration
#            # 이 정보는 console.cloud.google.com/apis 에 등록된 인증 정보에 있다.
#            clientId: 377825014181-2tpha7niq0hjar86e4j8h6dl0h8j1s3i.apps.googleusercontent.com
#            clientSecret: yyHXhXWBRrx3jyDWrhiSwzu8

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 377825014181-2tpha7niq0hjar86e4j8h6dl0h8j1s3i.apps.googleusercontent.com
            client-secret: yyHXhXWBRrx3jyDWrhiSwzu8
          #          facebook:
          #            client-id: 1108041866346884
          #            client-secret: f52f8eaab7cdd0272d37ab89e0335be1
          #          kakao:
          #            client-id: fa84d469d8038b6a422d1f9b2b6f9067
          #            client-secert: RuubX7J4HuhrekWplEeu2FnlSMiCftHH
          #            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
          #            authorization-grant-type: authorization_code
          #            client-name: kakao
          naver:
            client-id: bkdZjYp4EfmqIkZaEtqi
            client-secret: YLHoiLkdSy
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
            client-name: naver

        provider:
          #          kakao:
          #            authorization-uri: https://kauth.kakao.com/oauth/authorize
          #            token-uri: https://kauth.kakao.com/oauth/token
          #            user-info-uri: https://kapi.kakao.com/v2/user/me
          #            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response