spring:
  # Postgres Database
  datasource:
    url: jdbc:postgresql://localhost:5432/devplan
    username: plan
    password: plan
    driver-class-name: org.postgresql.Driver
  # JPA
  jpa:
    hibernate:
      ddl-auto: create # ???? ??? ?? (drop -> create)
    properties:
      hibernate:
        format_sql: true