spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
  batch:
    jdbc: # 내장 DB 일때 설정 가능
      initialize-schema: embedded


---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/inflearn_batch?useUnicode=true&characterEncoding=utf8
      username: inflearn_batch
      password: inflearn_batch
      driver-class-name: com.mysql.jdbc.Driver
  batch:
    jdbc: # schema-mysql.sql 항상 실행
      # 오류 발생 : Table 을 모두 삭제했는데, 자동 실행하는 부분이 never 일때는 테이블도 자동으로 생성되지 않기 때문
      # initialize-schema: never
      initialize-schema: always
    job:
      enabled: false # spring batch 자동실행 방지