# docker compose -f docker-compose.yml up -d --build
# docker compose -f docker-compose.yml build --no-cache
# redis-cli: docker exec -it {containerId} redis-cli
   # keys *
   # get key {keyName}
# postgresql
   # psql -U studyollejpa
   # create database studyolle;
   # grant all privileges on database studyolle to studyollejpa;
# API 테스트
  # Login 요청

version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: studyolle-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DATABASE: studyolle
      POSTGRES_USER: studyollejpa
      POSTGRES_ROOT_PASSWORD: 1234
      POSTGRES_HOST_AUTH_METHOD: "trust"
    networks:
      - internal-network
  studyolle:
    container_name: studyolle-kotlin
    build: ../
    ports:
      - "8081:8080"
    networks:
      - internal-network
networks:
  internal-network:
    driver: bridge