server:
  port: 8082

spring:
  application:
    name: my-first-service

eureka:
  client:
    fetch-registry: true  # true: 유레카 등록
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka