spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/expedia
    username: expedia
    password: 1234
    driver-class-name: org.postgresql.Driver
  # JPA
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true