spring:
  batch:
    job:
      names: ${job.name:NONE} # job names ? ??? (job.name ?? ??): job.name ????? ??? ?????. (?? ??????? ?? ??X)
#    jdbc:
#      initialize-schema: always

  # H2Database
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  # JPA
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
#  sql:
#    init:
#      schema-locations: classpath*:/schema.sql
#      data-locations: classpath*:/data.sql

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
