spring:
  batch:
    job:
      names: ${job.name:NONE}
    jdbc:
      initialize-schema: always

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  sql:
    init:
      data-locations: classpath*:/person.sql
