spring:
  h2:
    console:
      enabled: true # http://localhost:8080/h2-console

  jpa:
    show-sql: true # query 출력
    properties:
      hibernate:
        ddl-auto: create-drop # 항상 새로 생성하고, 종료되면 자동으로 drop 처리한다. (운영에선 none 대부분)
        format_sql: true # query format
    # ddl-auto 위에 속성이 좀더 세밀해서 이게 설정되면 아래 generate-ddl 속성을 무시한다.
    # false (default 값) : h2 DB (embedded) 사용했을땐 기본이 ddl-auto 속성이 create-drop 으로 동작한다.
    generate-ddl: false  # (jpa 의 하위속성) 구현체와 상관없이 자동화된 ddl 을 사용할 수 있도록 지정 (JPA 하위 속성)

  datasource:
    hikari:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/jpaapp?characeterEncoding=UTF-8&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: jpaapp
      password: jpaapp
  sql:
    init:
      mode: always  # schema.sql, data_test.sql 실행 (h2 DB(embedded)와 같은건 기본으로 설정되어있다)
       # ddl-auto 모드 둘 중에 이게 더 우선순위가 높다. schema.sql 이 있다면 ddl-auto 가 무시됨. (data_test.sql 만 있으면 상관없음)

#logging:
#  level:
#    org.hibernate.type: trace

server:
  port: 8070


