spring:
  h2:
    console:
      enabled: true # http://localhost:8080/h2-console

  jpa:
    show-sql: true # query 출력
    properties:
      hibernate:
        format_sql: true # query format

  datasource:
    hikari:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/jpaapp?characeterEncoding=UTF-8&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: jpaapp
      password: jpaapp

#logging:
#  level:
#    org.hibernate.type: trace

server:
  port: 8070


