spring:
  h2:
    console:
      enabled: true # http://localhost:8080/h2-console

  jpa:
    show-sql: true # query 출력
    properties:
      hibernate:
        format_sql: true # query format

server:
  port: 8070
